# Install Petals 4.2.0 on Ubuntu 12.10

# Build
# sudo docker run -p 7600:7600 -i -t petalslink/petals-esb /bin/bash

# Install
# sudo docker pull  petalslink/petals-esb

# Use
# cd /opt/petals && petals start
# open http://127.0.0.1:7600

FROM ubuntu:12.10

MAINTAINER Christophe Hamerling version: 0.1

RUN apt-get update

# install packages
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-6-jdk zip curl git-core build-essential

# env stuff
ENV PETALS_HOME /data/petals
ENV PETALS_VERSION 4.2.0
ENV PATH /opt/go/bin:/root/gocode/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#ENV HOSTNAME "$(hostname)"

# workaround to be able to resolve localhost from within Java
RUN sed -i "s/^127.0.0.1/127.0.0.1 $(hostname) /" /etc/hosts

# install petals
RUN curl -o /opt/petals.zip -L http://repository.ow2.org/nexus/content/groups/public/org/ow2/petals/petals-esb-enterprise-edition/${PETALS_VERSION}/petals-esb-enterprise-edition-${PETALS_VERSION}.zip
RUN unzip /opt/petals.zip -d /opt/
RUN unzip /opt/petals-esb-enterprise-edition-${PETALS_VERSION}/esb/petals-esb-default-zip-${PETALS_VERSION}.zip -d /opt/esb/

# Run petals
EXPOSE 7600
CMD cd /opt/esb/petals-esb-default-zip-${PETALS_VERSION}/bin && sh petals-esb.sh